# Site settings
title: TES Reborn
description: > # this means to ignore newlines until "baseurl:"
  TES Reborn is an IRC chat based roleplay
  set in the world of Tamriel from the Elder Scrolls game franchise.
baseurl: "/tesreborn" # the subpath of your site, e.g. /rps
url: "github.io/shadowlightwolf89/tesreborn" # the base hostname & protocol for your site

# Change this to where Jekyll should output the built site.
# ***WARNING***: Anything in this directory will be DELETED whenever Jekyll
# rebuilds the site!
destination: _site

# Build settings
markdown: kramdown
exclude:
  - LICENSE
  - README.md
  - Gemfile
  - Gemfile.lock
  - Rakefile

permalink: pretty

rp_convert: true

rp_tag_index: true
rp_tag_dir: /tags
rp_tag_index_layout: tag_index
rp_tag_title_prefix: "RPs tagged "

collections:
  # The RPs must be in a directory named exactly this, prefixed by an underscore.
  # So by default: _rps/
  # If you change this, you also need to change the collection key name in rp_log_converter.rb
  rps:
    output: true

defaults:
  -
    scope:
      path: ""
      type: rps # Needs to have the same name as the collection above
    values:
      canon: false
      complete: false
      format: [weechat]
      infer_char_tags: true
      layout: rp
      merge_text_into_rp: []
      permalink: /:path/
      rp_tags: ""
      strict_ooc: true

git:
  branch: gh-pages

transfer:
  command: robocopy
  settings: /mir
  source: _site\
  destination: git@github.com:shadowlightwolf89/tesreborn.git